/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux solimul-Zenbook-UP6502ZA-UP6502ZA 6.2.0-33-generic x86_64"
#define YALS_COMPILED "Wed 18 Oct 2023 03:20:16 PM MDT"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
